yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: bitnami-apache-kafka.eshopping.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false